### ISSUE TITLE
Instant Messaging

### ISSUE THREAD

**Issue by ryanmtran** [cs130-w22/Group-B4#4]
## Epic
As a user, I want to be able to be able to message others in near real-time to send and respond to texts in a timely manner.
## User Stories
- [x] As a user, I want to be able to access a messaging interface that displays texts in chronological order and provides an input to send messages
- [x] As a user, I want to be able to send messages and ensure that I only send messages to a specified individual
- [x] As a user, I want to be able to receive messages sent to me in near real-time and ensure that I only receive messages addressed to me
