### ISSUE TITLE
User Profile

### ISSUE THREAD

**Issue by henry-macarthur** [cs130-w22/Group-B4#5]
## Epic
As a User I want to be able to create and edit a profile that is representative of my interests

## Requirements 
A user will need to be authenticated to be able to see/edit their profile 
Will need to load data from the ucla course API to get a list of all valid tags 

## User Stories
- [x] add tags  : As a user I want to be able to select different tags (classes / activities) to add to my profile 
- [x] remove tags : As a user I want to be able to delete current tags on my profile
- [x] make profile viewable : As a user, I want other users to be able to see my profile
